package pl.pfm.logic.account;

import org.springframework.stereotype.Service;
import pl.pfm.model.account.Account;

import java.util.ArrayList;
import java.util.List;

@Service
public class AccountValidator {

    public List<String> validate(Account account) {
        List<String> errors = new ArrayList<>();

        if (account.getId() != null) {
            errors.add("Account id must not be provided, it's generated by the application");
        }

        if (account.getName() == null || "".equals(account.getName())){
            errors.add("Account name must not be empty");
        }

        if (account.getValue() == null){
            errors.add("Account value must be specified");
        }

        return errors;
    }

}
